name: flutter_heritage_mada
description: "Application de découverte du patrimoine historique et culturel de Madagascar"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- GESTION D'ÉTAT & ARCHITECTURE ---
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  equatable: ^2.0.5

  # --- NAVIGATION ---
  go_router: ^14.2.0

  # --- RESEAU & API ---
  dio: ^5.5.0
  json_annotation: ^4.9.0

  # --- CARTOGRAPHIE (PostGIS compatible) ---
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # --- MODE HORS-LIGNE (Base de données locale) ---
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.24
  http: ^1.6.0
  shared_preferences: ^2.2.3  # <--- Ajouté pour le cache rapide des récits
  connectivity_plus: ^6.0.3   # <--- Ajouté pour détecter la connexion Internet

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Générateurs de code (pour Drift et JSON)
  build_runner: ^2.4.11
  drift_dev: ^2.20.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/