name: heritage_mada_backend
description: "Le serveur API Dart Frog pour HeritageMada"
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  dart_frog: ^1.1.0
  
  postgres: ^3.0.7
  
  dotenv: ^4.2.0

dev_dependencies:
  test: ^1.24.0